---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/24-9-19/violin23.9.19.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/299892/articles/442474/master/folder/figures/24-9-19"
    url: "/users/299892/articles/442474/master/file/figures/24-9-19/violin23.9.19.html"
export-filename: violin23.9.19.png
web-height: 500px
