---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/responsiveTF_diversity_kmeans/responsiveTF_diversity_kmeans.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/299892/articles/442474/master/folder/figures/responsiveTF_diversity_kmeans"
    url: "/users/299892/articles/442474/master/file/figures/responsiveTF_diversity_kmeans/responsiveTF_diversity_kmeans.png"
