---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/promoter_luminescence_corrected/promoter_luminescence.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/299892/articles/448036/master/folder/figures/promoter_luminescence_corrected"
    url: "/users/299892/articles/448036/master/file/figures/promoter_luminescence_corrected/promoter_luminescence.png"
