---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/log2fold/log2fold.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/299892/articles/442474/master/file/figures/log2fold/log2fold.png"
    folder_url: "/users/299892/articles/442474/master/folder/figures/log2fold"
